### ISSUE TITLE
Missing the information in "About" field

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.zh-CN#24]
Missing the Link to "Github Pages"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by VietTran0302** [comment]
Hi,

Please refer the below screenshot.
![image](https://user-images.githubusercontent.com/64255878/168540399-429b35c2-1fab-427f-a347-da4b575907fd.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/185041776-b3fe9ecb-c0f3-4341-9335-70e02538c91c.png)

fixed.
