### ISSUE TITLE
Student + LAK Instructions documents have a Note with leading spaces, leading to undesired rendering.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.zh-CN#25]
This line, in the starting section of all student + LAK lab instructions appears to have ~16 additional/unneeded spaces:

                **注意：** 我们提供 **[交互式实验室模拟](https://mslabs.cloudguides.com/guides/AZ-801%20Lab%20Simulation%20-%20Configuring%20security%20in%20Windows%20Server)** ，让你能以自己的节奏点击浏览实验室。 你可能会发现交互式模拟与托管实验室之间存在细微差异，但演示的核心概念和思想是相同的。

This leads to undesirable display in both Github and ALH rendering:

![image](https://user-images.githubusercontent.com/49700217/228916846-6bf42ff4-c9c6-4c0d-be66-2019650b172d.png)

If one removes the leading spaces, it displays as expected:

**注意：** 我们提供 **[交互式实验室模拟](https://mslabs.cloudguides.com/guides/AZ-801%20Lab%20Simulation%20-%20Configuring%20security%20in%20Windows%20Server)** ，让你能以自己的节奏点击浏览实验室。 你可能会发现交互式模拟与托管实验室之间存在细微差异，但演示的核心概念和思想是相同的。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7U3RhcnRzIFdpdGg7TEFCX0FLXzwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgR3JvdXA7RXF1YWw7V1dMLUxBQi1BWi04MDFfbWFzdGVyPC9RUj48UVIgSWQ9IjQiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0NoaW5lc2UgKFNpbXBsaWZpZWQpPC9RUj48UVIgSWQ9IjYiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7Q29udGFpbnM7NTAzMzU8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d) to update
The following were at PHO and so blocked from updating at the moment.
LAB_AK_06_Upgrade_and_migrate_Windows Server.md
LAB_AK_02_Implementing_security_solutions_hybrid_scenarios.md
LAB_AK_07_Implementing_migration_in_hybrid_scenarios.md
LAB_AK_05_Implementing_Azure-based_recovery_services.md
LAB_AK_09_Implementing_operational_monitoring_in_hybrid_scenarios.md

**Comment by chriscarty00** [comment]
Discussed with and we made the decision to update the older Handedback locfiles which will seed the TM and the update would be taken by the newer locfile
